<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerREfDyL2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerREfDyL2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerREfDyL2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerREfDyL2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerREfDyL2\App_KernelDevDebugContainer([
    'container.build_hash' => 'REfDyL2',
    'container.build_id' => '69ad0b8c',
    'container.build_time' => 1693126470,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerREfDyL2');
