<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKRR2cNX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKRR2cNX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKRR2cNX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKRR2cNX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKRR2cNX\App_KernelDevDebugContainer([
    'container.build_hash' => 'KRR2cNX',
    'container.build_id' => 'fbb5f6fd',
    'container.build_time' => 1692728384,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKRR2cNX');
